package com.drools.example

import com.drools.example.HelloWorldTest.Osoba
import com.drools.example.HelloWorldTest.Plec
import com.drools.example.HelloWorldTest.Relacja
import com.drools.wypozyczalnia.Samochod
import com.drools.wypozyczalnia.KlasaSamochodu
import com.drools.wypozyczalnia.Klient

rule "Init"
	when
	then
		insert(new Samochod(KlasaSamochodu.A));
		insert(new Samochod(KlasaSamochodu.A));
		insert(new Samochod(KlasaSamochodu.B));
		insert(new Samochod(KlasaSamochodu.D));
		insert(new Samochod(KlasaSamochodu.D));

		insert(new  Klient(false, KlasaSamochodu.BRAK,"11/11/2015","12/11/2015",new String[]{"fotelik","bagaznik"}));
//		System.out.println("XD");
//
//		insert(new Relacja(maria,marek,"rodzic"));

end

rule "Auto"
	when
		samochod: Samochod(!isInited())
	then
		System.out.println("Zarejestrowany nowy samochod klasy "+ samochod.getKlasaSamochodu());
		samochod.setInited(true);
		update(samochod);

end
