package com.drools.example

import com.drools.example.HelloWorldTest.Osoba
import com.drools.example.HelloWorldTest.Plec
import com.drools.example.HelloWorldTest.Relacja

rule "Init"
	when
	then
		Osoba maria          = new Osoba("Maria");
		Osoba ewa            = new Osoba("Ewa");
		Osoba agata          = new Osoba("Agata");
		Osoba anna           = new Osoba("Anna");
		Osoba agnieszka      = new Osoba("Agnieszka");
		Osoba beata          = new Osoba("Beata");
		Osoba iwona          = new Osoba("Iwona");
		Osoba joanna         = new Osoba("Joanna");
		Osoba piotr          = new Osoba("Piotr");
		Osoba adam           = new Osoba("Adam");
		Osoba marek          = new Osoba("Marek");
		Osoba robert         = new Osoba("Robert");
		Osoba jan            = new Osoba("Jan");
		Osoba krzysztof      = new Osoba("Krzysztof");
		Osoba radek          = new Osoba("Radek");
		Osoba darek          = new Osoba("Darek");
		Osoba tomek          = new Osoba("Tomek");
		Osoba jacek          = new Osoba("Jacek");

		insert(new Relacja(maria,marek,"rodzic"));
		insert(new Relacja(maria,agata,"rodzic"));
		insert(new Relacja(maria,jan,"rodzic"));
		insert(new Relacja(piotr,marek,"rodzic"));
		insert(new Relacja(piotr,agata,"rodzic"));
		insert(new Relacja(piotr,jan,"rodzic"));
		insert(new Relacja(ewa,anna,"rodzic"));
		insert(new Relacja(ewa,joanna,"rodzic"));
		insert(new Relacja(ewa,krzysztof,"rodzic"));
		insert(new Relacja(adam,anna,"rodzic"));
		insert(new Relacja(adam,joanna,"rodzic"));
		insert(new Relacja(adam,krzysztof,"rodzic"));
		insert(new Relacja(agata,radek,"rodzic"));
		insert(new Relacja(agata,beata,"rodzic"));
		insert(new Relacja(robert,radek,"rodzic"));
		insert(new Relacja(robert,beata,"rodzic"));
		insert(new Relacja(anna,darek,"rodzic"));
		insert(new Relacja(anna,tomek,"rodzic"));
		insert(new Relacja(jan,darek,"rodzic"));
		insert(new Relacja(jan,tomek,"rodzic"));
		insert(new Relacja(agnieszka,jacek,"rodzic"));
		insert(new Relacja(agnieszka,iwona,"rodzic"));
		insert(new Relacja(krzysztof,jacek,"rodzic"));
		insert(new Relacja(krzysztof,iwona,"rodzic"));
end

rule "NadajKobiete"
	when
		o: Osoba(getPlec()==Plec.NIEZNANA && imie.charAt(imie.length()-1)=='a')
	then
		o.setPlec(Plec.KOBIETA);
		//System.out.println(o.toString());
		update(o);

end

rule "NadajMezczyzne"
	when
		o: Osoba(getPlec()==Plec.NIEZNANA && imie.charAt(imie.length()-1)!='a')
	then
		o.setPlec(Plec.MEZCZYZNA);
		//System.out.println(o.toString());
		update(o);
end

rule "RelacjaNadajacaPlec"
	when
		r: Relacja(r.o1().getPlec()==Plec.NIEZNANA || r.o2().getPlec()==Plec.NIEZNANA)
	then
		insert(r.o1());
		insert(r.o2());
		update(r);
end

rule "Madka"
	when
		r: Relacja(r.o1().getPlec()==Plec.KOBIETA, relacja=="rodzic")
	then
		System.out.println(r.o1()+" jest MADKOM "+r.o2());
end

rule "Ojdziedz"
	when
		r: Relacja(r.o1().getPlec()==Plec.MEZCZYZNA, relacja=="rodzic")
	then
		System.out.println(r.o1()+" jest OJDŹCEM "+r.o2());
end
